/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var s=b.document,z=b.navigator,M="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),N=!1,x=0,B=[],t=[],n=[],l=[],r={},G=0,H=[],E=null,X={},y={},ia=null,u,Y=[].slice,ja,Z,O,k,C,$,P,ka,la,ma,I,aa,Q,R,na,J,oa,pa,qa,ra,w,sa,D,S,ta,ba,ua,va,ca,q,wa,da,T,U,xa,ya,V,za,ea,fa,Aa,ga,F,K,L,W,ha,v=function(a){try{return{init:R,hash:Q,
rules:xa,hasRules:V,defaults:Aa,__qc:function(){return!0}}[a].apply(null,Y.call(arguments,1))}catch(c){return!1}};v.evts=0;v.v=2;v.SD=M;v.qpixelsent=[];U=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};fa=function(a){(a=a||b._qacct)&&(ca(l,a)||l.push(a))};ca=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};da=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};T=function(a){var c,d;c=da(a);if("array"===c)return a.slice(0);
if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};V=function(a){return ca(n,a)};Aa=function(a,c){var d;a&&((d=X[a])&&(c=W(c,d)),c.qacct&&delete c.qacct,X[a]=c)};ga=function(a){var c,d;if(k(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?w(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=y[d])?W(c,a):a,y[d]=c);fa(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ga(a[c])};W=
function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ba(d,a,c);ba(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ba=function(a,c,d){var b,f,h,A,k,m;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(f=c[b],h=d[b],A="",k=!!f&&"string"==typeof f,m=!!h&&"string"==typeof h,
k&&(A=f),k&&m&&(A+=","),m&&(A+=h),a[b]=A)};F=function(){var a=[],c,d;if(!(0<G)){wa();for(c in y)y.hasOwnProperty(c)&&y[c]&&(d=y[c],a.push(d),delete y[c]);1==a.length&&w(a[0]);1<a.length&&w(a)}};K=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],V(b)||c.push(b);if(0===c.length)F();else for(d=0;d<c.length;d++)b=c[d],n.push(b),ua(b)};va=function(){for(var a;H[0]&&("loaded"==H[0].readyState||"complete"==H[0].readyState);)a=H.shift(),a.onreadystatechange=null,E.parentNode.insertBefore(a,E),L()};
ua=function(a){var c,d;c=("https:"===s.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";E=E||s.scripts[0];G++;d=s.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){r[a]=0;L()},d.onerror=function(){r[a]=1;L()},E.parentNode.insertBefore(d,E)):d.readyState?(r[a]=2,H.push(d),d.onreadystatechange=va,d.src=c):(r[a]=4,L())};L=function(){G-=0<G?1:0;F()};xa=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ga(c):w(c,!0)};for(c=0;c<arguments.length;c++)d=
Y.call(arguments[c],0),d.splice(1,0,b),ya.apply(null,d);a=!1;N&&F()}};ya=function(a,c){var d=[],b=[],f=c||w,h,A,k,m,p;if((h=Y.call(arguments,2))&&h.length){A=h[0]||U;k=h[1];m=h[2];h=m.length;for(p=0;p<h;p++)d.push(!1),b.push(null);d={p:a,f:d,r:A,c:m,a:k,v:b};V(a)||n.push(a);t.push(d);za(d,f)}};za=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,e;try{b=a.c[d][0],e=a.c[d].slice(1),e.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;ea(a,c)}),b.apply(null,e)}catch(k){a.f[d]=!0,
a.v[d]=!1,ea(a,c)}})(b)};ea=function(a,c){var d=a.a,b=a.v,f=a.r||U,h,k,t,m,p,g;(h=U(a.f))&&(h=h&&f(b));if(h)for(b=0;b<d.length;b++)try{k=d[b][0];t=1<d[b].length?d[b].slice(1):[];t=t.concat(a.v);m=k.apply(null,t);p={qacct:a.p,event:"rule"};for(g in m)m.hasOwnProperty(g)&&"qacct"!==g&&(p[g]=m[g]);c(p)}catch(l){}};ja=function(){return Z(0)!==Z(6)?1:0};Z=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};O=function(a){return a.replace(/\./g,
"%2E").replace(/,/g,"%2C")};C="function"===typeof encodeURIComponent?encodeURIComponent:O;k=function(a){return"undefined"!=typeof a&&null!=a};$=function(){return Math.round(2147483647*Math.random())};P=function(a){var c="",d=s.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};ka=function(){var a="",c=I(),b,e,f;if(1===x)return";fpan\x3du;fpa\x3d";b=Q(c);for(e=0;e<M.length;e++)if(M[e]===b)return";fpan\x3du;fpa\x3d";
b=new Date;e=P("__qca");if(0<e.length){try{f=+e.split("-")[2],338688E5<b-f&&(s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(f+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(h){}a+=";fpan\x3d0;fpa\x3d"+e}0===P("__qca").length&&(e="P0-"+$()+"-"+b.getTime(),s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),e=P("__qca"),a=0<e.length?a+(";fpan\x3d1;fpa\x3d"+e):a+";fpan\x3du;fpa\x3d");return a};la=function(a){s.cookie=
a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+I()};I=function(){var a,c,b,e;a=s.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");e=c.length;if(3>e)return a;b=c[e-1];return 3>b.length?a:a=c[e-2]+"."+b};aa=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};Q=function(a){var c;c=aa(2166136261,a);a=aa(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};S=function(a,c,d){var e=
"",f=b._qacct,h=null,t="webpage",l="load",m={},p,g,f=c?c.qacct||b._qacct:b._qacct;p=y[f];c?p&&(c=W(c,p)):c=p;f&&delete y[f];if(null!=c)for(g in c)m[g]=!0,c.hasOwnProperty(g)&&"string"===typeof g&&"string"===typeof c[g]&&("uid"===g||"uh"===g?(na()||(h=Q(c[g])),delete c[g]):"qacct"!==g&&(e+=";"+g+a+"\x3d"+C(c[g]),"media"===g&&(t=c[g]),"event"===g&&(l=c[g])));if("string"!==typeof f){if(!k(b._qacct)||0===b._qacct.length)return"";f=b._qacct}if(f&&(p=X[f]))for(g in p)"string"===typeof g&&p.hasOwnProperty(g)&&
!m[g]&&(e+=";"+g+a+"\x3d"+C(p[g]),"media"===g&&(t=p[g]),"event"===g&&(l=p[g]));m=r[f];k(m)||(m=3);e+=";rf"+a+"\x3d"+m;"string"===typeof h&&(c.uh=h,e+=";uh"+a+"\x3d"+C(h));if("webpage"===t&&"load"===l){for(c=0;c<v.qpixelsent.length;c++)if(v.qpixelsent[c]===f&&!d)return"";v.qpixelsent.push(f)}"ad"===t&&(x=1);return";a"+a+"\x3d"+f+e};ta=function(){var a=s.getElementsByTagName("meta"),c="",b,e,f,h;for(b=0;b<a.length;b++){f=a[b];if(1E3<=c.length)return c;k(f)&&k(f.attributes)&&k(f.attributes.property)&&
k(f.attributes.property.value)&&k(f.content)&&(e=f.attributes.property.value,f=f.content,3<e.length&&"og:"===e.substring(0,3)&&(0<c.length&&(c+=","),h=80<f.length?80:f.length,c+=O(e.substring(3,e.length))+"."+O(f.substring(0,h))))}return C(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;k(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());
return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};w=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",e=$(),f="",h="",t="",l="",m="",p="u",g="1",n=0,r=[],q,u,w,y;x=0;k(v.qpixelsent)||(v.qpixelsent=[]);if(k(a))for(q in a)if("string"==typeof a[q]){h=S("",a,c);break}else"object"==typeof a[q]&&null!=a[q]&&(++n,h+=S("."+n,a[q],c));else"string"===typeof _qacct&&(h=S("",null,c));0!==h.length&&(n=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(p=z.javaEnabled()?
"1":"0"),k(b._qmeta)&&(t=";m\x3d"+C(b._qmeta),b._qmeta=null),self.screen&&(f=screen.width+"x"+screen.height+"x"+screen.colorDepth),u=new Date,w=ja(),y=ka(),b.location&&b.location.href&&(l=C(b.location.href)),s&&s.referrer&&(m=C(s.referrer)),b.self===b.top&&(g="0"),q=ta(),r.push("/pixel;r\x3d"+e+h+y+";ns\x3d"+g+";ce\x3d"+n),r.push(";je\x3d"+p+";sr\x3d"+f+";enc\x3d"+d+";dst\x3d"+w+";et\x3d"+u.getTime()+";tzo\x3d"+u.getTimezoneOffset()+t+";ref\x3d"+m+";url\x3d"+l+";ogl\x3d"+q),B.push(r),D())};sa=function(a){var c=
new Image;a=[b.location.protocol,"//pixel.",oa(u)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(u),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&la("__qca")}};D=function(){if(u)for(;B.length;)sa(B.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||k(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!k(u)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");
return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}u=1}D()};pa=function(a,c){u=PrivacyManagerAPI.callApi(a,"quantserve.com",I(),"truste.com",c);D()};qa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:I(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",J,!1);else if(b.attachEvent)b.attachEvent("onmessage",J);else{u=!0;D();return}try{b.top.postMessage(JSON.stringify(d),
"*")}catch(e){}ia=setTimeout(function(){k(u)||(u=!0,D())},25)};J=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",J,!1):b.detachEvent&&window.detachEvent("onmessage",J),u=c.PrivacyManagerAPI,D())}};ha=function(){var a=arguments,c,b;q([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],w(c);l.length?K(l.slice(0)):F()};q=function(a){var c=
da(a);if("array"===c)for(c=0;c<a.length;c++)q(a[c]);else"object"===c&&fa(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||w({qacct:b._qacct});if(!v.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&w(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&w(b.ezt[a]);b._qevents={push:ha};b.ezt.push=function(){var a=arguments,d;if(k(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ha.apply(this,arguments)};v.evts=1}};R=
function(){var a;k(b._qevents)||(b._qevents=[]);k(b.ezt)||(b.ezt=[]);b._qoptions&&(a=T(b._qoptions),q(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=T(b.qcdata),q(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=T(b.smarttagdata),q(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);v.evts||(b._qevents.push=function(){q([].slice.call(arguments));K(l.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){q([].slice.call(arguments));K(l.slice(0));
return[].push.apply(b.ezt,arguments)});q(b.ezt);q(b._qevents);q({qacct:b._qacct});b._qoptions=null;l.length?K(l.slice(0)):F();N=!0};b.quantserve=b.quantserve||R;v.quantserve=R;return v}(window);
try{__qc("hasRules","p-WxfSuuBK1Tnn5")||function(b,s,z){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(M){}var N=function(b,n,l){return b?"nc"===b?!n||!l||0>n.indexOf(l):"eq"===b?n===l:"sw"===b?0===n.indexOf(l):"ew"===b?(b=n.length-l.length,n=n.lastIndexOf(l,b),-1!==n&&n===b):"c"===b?0<=n.indexOf(l):!1:!1},x=function(b,n,l){var r;if(s.top===s.self)r=z.location.href;else{r=z.referrer;var x=z.createElement("a");x.href=r;r=x.href}N(n,r,l)?b(r):b(!1)},B=function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[B,"_fp.event.Homepage"]],[[x,"eq","https://www.solodev.com/"]]],[b,null,[[B,"_fp.event.Customers"]],[[x,"eq","https://www.solodev.com/customers/"]]],[b,null,[[B,"_fp.event.Pricing"]],[[x,"sw","https://www.solodev.com/pricing/"]]],[b,null,[[B,"_fp.event.Features"]],[[x,"sw","https://www.solodev.com/features/"]]],[b,null,[[B,"_fp.event.Blog"]],[[x,"eq","https://www.solodev.com/blog/"]]])}("p-WxfSuuBK1Tnn5",window,document)}catch(nfe$$4){}quantserve();
try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};